package com.example.noleggio.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.example.noleggio.model.PrenotazioniAuto;
import com.example.noleggio.repo.PrenotazioniAutoRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path="/prenotazioniAuto") // This means URL's start with /noleggio (after Application path)
public class PrenotazioniAutoController {
	@Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	private PrenotazioniAutoRepository prenotazioniAutoRepository;
	@CrossOrigin(origins = "http://localhost:4200")
	@GetMapping(path="/getPrenotazioniAuto/{id}")
		 public @ResponseBody Iterable<PrenotazioniAuto>/*Optional<utenti>*/ getPrenotazioniAuto() {
			    // This returns a JSON or XML with the users
				  return prenotazioniAutoRepository.findAll();
		 }
	}
